CREATE TABLE CPU (
    maCPU INT PRIMARY KEY NOT NULL,
    tenCPU VARCHAR(50) NOT NULL
);

CREATE TABLE RAM (
    maRAM INT PRIMARY KEY NOT NULL,
    dungLuongRAM INT NOT NULL
);

CREATE TABLE ROM (
    maROM INT PRIMARY KEY NOT NULL,
    dungLuongROM INT NOT NULL
);

CREATE TABLE THUONGHIEU (
    maTH INT PRIMARY KEY NOT NULL,
    tenTH NVARCHAR(100) NOT NULL
);

CREATE TABLE DOPHANGIA (
    maDPG INT PRIMARY KEY NOT NULL,
    tenDPG VARCHAR(50) NOT NULL
);

CREATE TABLE PHANLOAI (
    maLoai INT PRIMARY KEY NOT NULL,
    tenLoai VARCHAR(50) NOT NULL
);

CREATE TABLE NHACUNGCAP (
    maNCC INT PRIMARY KEY NOT NULL,
    tenNCC NVARCHAR(100) NOT NULL,
    diaChi NVARCHAR(100) NOT NULL,
    sdt VARCHAR(11) NOT NULL
);

CREATE TABLE CHUCNANG (
    maCN INT PRIMARY KEY NOT NULL,
    tenCN NVARCHAR(50) NOT NULL
);

CREATE TABLE QUYEN (
    maQuyen INT PRIMARY KEY NOT NULL,
    tenQuyen NVARCHAR(50) NOT NULL
);

CREATE TABLE SANPHAM (
    maSP INT PRIMARY KEY NOT NULL,
    tenSP VARCHAR(50) NOT NULL,
    giaSP INT NOT NULL,
    soLuongTon INT,
    maCPU INT NOT NULL,
    maRAM INT NOT NULL,
    maROM INT NOT NULL,
    maTH INT NOT NULL,
    maDPG INT NOT NULL,
    maLoai INT NOT NULL,
    thoigianBH INT,
    FOREIGN KEY (maCPU) REFERENCES CPU(maCPU),
    FOREIGN KEY (maRAM) REFERENCES RAM(maRAM),
    FOREIGN KEY (maROM) REFERENCES ROM(maROM),
    FOREIGN KEY (maTH) REFERENCES THUONGHIEU(maTH),
    FOREIGN KEY (maDPG) REFERENCES DOPHANGIA(maDPG),
    FOREIGN KEY (maLoai) REFERENCES PHANLOAI(maLoai)
);

CREATE TABLE NHANVIEN (
    maNV INT PRIMARY KEY NOT NULL,
    tenNV NVARCHAR(50) NOT NULL,
    taiKhoan VARCHAR(50) NOT NULL,
    matKhau VARCHAR(50) NOT NULL,
    sdt VARCHAR(11),
    email VARCHAR(100) NOT NULL,
    maQuyen INT NOT NULL,
    FOREIGN KEY (maQuyen) REFERENCES QUYEN(maQuyen)
);

CREATE TABLE KHACHHANG (
    maKH INT PRIMARY KEY NOT NULL,
    tenKH NVARCHAR(50) NOT NULL,
    sdt VARCHAR(11),
    email VARCHAR(100)
);

CREATE TABLE PHIEUNHAP (
    maPN INT PRIMARY KEY NOT NULL,
    maNV INT NOT NULL,
    maNCC INT NOT NULL,
    tongTien INT NOT NULL,
    ngayNhap DATE NOT NULL,
    FOREIGN KEY (maNV) REFERENCES NHANVIEN(maNV),
    FOREIGN KEY (maNCC) REFERENCES NHACUNGCAP(maNCC)
);

CREATE TABLE PHIEUXUAT (
    maPX INT PRIMARY KEY NOT NULL,
    maNV INT NOT NULL,
    maKH INT NOT NULL,
    tongTien INT NOT NULL,
    ngayXuat DATE NOT NULL,
    FOREIGN KEY (maNV) REFERENCES NHANVIEN(maNV),
    FOREIGN KEY (maKH) REFERENCES KHACHHANG(maKH)
);

CREATE TABLE PHIEUBAOHANH (
    maPBH INT PRIMARY KEY NOT NULL,
    maSP INT NOT NULL,
    maPX INT NOT NULL,
    maNV INT NOT NULL,
    ngayTiepNhan DATE,
    moTaLoi NVARCHAR(100),
    trangThaiBH INT,
    FOREIGN KEY (maSP) REFERENCES SANPHAM(maSP),
    FOREIGN KEY (maPX) REFERENCES PHIEUXUAT(maPX),
    FOREIGN KEY (maNV) REFERENCES NHANVIEN(maNV)
);

CREATE TABLE CHITIETPHIEUNHAP (
    maSP INT NOT NULL,
    maPN INT NOT NULL,
    soLuongSP INT NOT NULL,
    giaNhap INT NOT NULL,
    PRIMARY KEY (maSP, maPN),
    FOREIGN KEY (maSP) REFERENCES SANPHAM(maSP),
    FOREIGN KEY (maPN) REFERENCES PHIEUNHAP(maPN)
);

CREATE TABLE CHITIETPHIEUXUAT (
    maSP INT NOT NULL,
    maPX INT NOT NULL,
    giaBan INT NOT NULL,
    soLuongSP INT NOT NULL,
    serialSP VARCHAR(50) NOT NULL,
    PRIMARY KEY (maSP, maPX),
    FOREIGN KEY (maSP) REFERENCES SANPHAM(maSP),
    FOREIGN KEY (maPX) REFERENCES PHIEUXUAT(maPX)
);

CREATE TABLE CHITIETCHUCNANG (
    maCN INT NOT NULL,
    maQuyen INT NOT NULL,
    PRIMARY KEY (maCN, maQuyen),
    FOREIGN KEY (maCN) REFERENCES CHUCNANG(maCN),
    FOREIGN KEY (maQuyen) REFERENCES QUYEN(maQuyen)
);

INSERT INTO QUYEN (maQuyen, tenQuyen) VALUES
(1, 'Quản trị viên (Admin)'),
(2, 'Kế toán'),
(3, 'Nhân viên bán hàng'),
(4, 'Nhân viên bảo hành'),
(5, 'Quản lí kho');

INSERT INTO NHANVIEN (maNV, tenNV, taiKhoan, matKhau, sdt, email, maQuyen) VALUES
(1, 'Phạm Đình Duy Thái', 'duythai', '123456', '0905123456', 'dthai@example.com', 1),
(2, 'Trần Thị B', 'tranthib', 'password123', '0905234567', 'tranthib@example.com', 2),
(3, 'Lê Văn C', 'levanc', 'password123', '0905345678', 'levanc@example.com', 3),
(4, 'Phạm Thị D', 'phamthid', 'password123', '0905456789', 'phamthid@example.com', 4),
(5, 'Hoàng Văn E', 'hoangvane', 'password123', '0905567890', 'hoangvane@example.com', 5);


